### ISSUE TITLE
djs v13 Upgrade

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/genesis#465]
**Summary:**
well, v13 of discord.js is in development. 

So, Genesis is getting an upgrade.

As always, I'd love help and input! this will all happen on the v13 branch.

**Todo:**

- [x] c71042888010d0b45aa3b8903c96814e3f3197d5 Set up interaction handler
- [x] c71042888010d0b45aa3b8903c96814e3f3197d5 Create model for command interactions
- [x] Handle Button interactions
- [x] Handle Message Component interactions
- [x] Handle Select Menus
- [x] #500
    - [x] Don't make elevated commands visible to everyone at startup
    - [x] Map roles whenever roles are updated for each guild. (this seems like a really messy way)
    - [x] Skip execution for ineligible callers
- [x] Migrate commands
    - [x] #468
    - [x] OnDemand
        - [x] #469
        - [x] #470
        - [x] #471
        - [x] #472
        - [x] #473
        - [x] #474
        - [x] #475
        - [x] #476
        - [x] #477
    - [x] c71042888010d0b45aa3b8903c96814e3f3197d5 Pricechecks
    - [x] #478
    - [x] #479
    - [x] #467
    - [x] #480 
    - [x] #481
    - [x] #482
    - [x] #483
    - [x] #484
    - [x] #485
    - [x] #486
    - [x] #487
    - [x] #488
    - [x] "sudo" commands
        - [x] aaaec70373166c78173a7007de5a614c3f39cbd0 Restart
        - [x] aaaec70373166c78173a7007de5a614c3f39cbd0 Reload
        - [x] #495
        - [x] #494
        - [x] #493
        - [x] #492
- [x] #496
- [x] #489
- [x] #490
- [x] #491
